# Generated by Django 5.1 on 2024-09-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_waitlistentry_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlistentry',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='waitlistentry',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
